---
- hosts: all
  become: yes
  tasks: 
  - name: update node
    apt:
      name: apt-update
      update_cache: yes
  - name: install java 
    apt:
      name: openjdk-8-jdk    
      state: present 
  - name: install tomcat8
    apt:
      name: tomcat8
      state: present
    notify: 
      - start tomcat8
      - enable tomcat8
  - name: deploy app 
    get_url:
      url: https://qt-s3-new-testing.s3-us-west-2.amazonaws.com/gameoflife.war
      dest: /var/lib/tomcat8/webapps
  handlers:
  - name: start tomcat8
    service:
      name: tomcat8
      state: started 
  - name: enable tomcat8
    service:
      name: tomcat8
      enabled: yes
  




        
